"""
Exports approved artifacts as GitHub issues. Export happens only after human approval and when a write token is provided.
Without a write token, it automatically behaves as dry-run.
"""
import hashlib
import json
import os
from pathlib import Path
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from src.validation import sanitize_text, validate_export_artifact, validate_review_record 

DEFAULT_TIMEOUT_SECONDS = 10
RETRY_TOTAL = 3
RETRY_BACKOFF_FACTOR = 0.5
RETRY_STATUS_CODES = (429, 500, 502, 503, 504)
EXPORT_MARKERS_DIRNAME = "export_markers"
MARKER_SCHEMA_VERSION = "2"

ARTIFACT_TITLES = {
    "evil_user_story": "Evil user story",
    "verification_test": "Verification test",
}

class GitHubIssueExporter:
    """
    Creates one GitHub issue per approved artifact, idempotently. Runs live automatically once a write token is configured; otherwise
    runs in dry-run so nothing is silently skipped or misconfigured. Pass dry_run explicitly to force one mode regardless of token (ex: tests).
    """
    def __init__(self, repo: str, token: str = None, dry_run: bool = None,
                 timeout: int = DEFAULT_TIMEOUT_SECONDS, session: requests.Session = None,
                 markers_dir: str = None):
        self.repo = repo
        # Deliberately a *separate* credential from GITHUB_API (read-only milestone/issue access) - least privilege for the write path.
        self.token = token or os.environ.get("GITHUB_API")
        """
         dry_run=None (the default) means "decide from whether a write token is configured" - this is what makes export actually live
        once credentials are provided, with no separate flag to remember to flip.
        """
        self.dry_run = (not self.token) if dry_run is None else dry_run
        self.timeout = timeout
        project_root = Path(__file__).resolve().parents[2]
        self.markers_dir = Path(markers_dir) if markers_dir else project_root / "outputs" / EXPORT_MARKERS_DIRNAME
        self.markers_dir.mkdir(parents=True, exist_ok=True)
        self.session = session or requests.Session()
        retry = Retry(
            total=RETRY_TOTAL,
            backoff_factor=RETRY_BACKOFF_FACTOR,
            status_forcelist=RETRY_STATUS_CODES,
            allowed_methods=frozenset({"POST"}),
            raise_on_status=False,
        )
        self.session.mount("https://", HTTPAdapter(max_retries=retry))

    def _idempotency_key(self, review_record: dict) -> str:
        basis = (
            f"{review_record['artifact_type']}:{review_record['source_threat_id']}:"
            f"{review_record['source_card_id']}:{review_record['text']}:"
            f"{review_record['source_milestone_number']}:{review_record.get('model')}:"
            f"{review_record.get('prompt_template_version')}:{MARKER_SCHEMA_VERSION}"
        )
        return hashlib.sha256(basis.encode("utf-8")).hexdigest()

    def _marker_path(self, key: str) -> Path:
        return self.markers_dir / f"{key}.json"

    def _build_title_and_body(self, artifact: dict, key: str) -> tuple:
        label = ARTIFACT_TITLES[artifact["artifact_type"]]
        title = sanitize_text(f"[ThreatSutra] {label}: {artifact['text']}"[:250])
        body = sanitize_text(
            f"{artifact['text']}\n\n"
            "---\n"
            "_Generated by ThreatSutra and approved through the human review gate "
            " Not directly authored by a maintainer._\n\n"
            f"- Source threat: `{artifact['source_threat_id']}`\n"
            f"- Source card: `{artifact['source_card_id']}`\n"
            f"- Milestone: #{artifact['source_milestone_number']}\n"
            f"<!-- threatsutra-marker:{key} -->\n"
        )
        return title, body

    def export(self, review_record: dict) -> dict:
        """
        Exports one artifact from its persisted review record. Note that:the exporter validates the record and independently checks
        decision == 'approve' itself, rather than trusting its caller. Returns a result dict describing what happened (dry_run /
        already_exported / created) - never raises for the "already exported" case, since that is the expected idempotent path.
        """
        validate_review_record(review_record)
        artifact = {
            "artifact_type": review_record["artifact_type"],
            "text": review_record["text"],
            "source_threat_id": review_record["source_threat_id"],
            "source_card_id": review_record["source_card_id"],
            "source_milestone_number": review_record["source_milestone_number"],
        }
        validate_export_artifact(artifact)
        key = self._idempotency_key(review_record)
        marker_path = self._marker_path(key)
        
        try:
            fd = os.open(marker_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            with os.fdopen(fd, "w") as f:
                f.write('{"status": "pending"}')
        except FileExistsError:
            return {"status": "already_exported", "marker": json.loads(marker_path.read_text())}
            
        title, body = self._build_title_and_body(artifact, key)
        if self.dry_run:
            marker_path.unlink()
            return {"status": "dry_run", "title": title, "body": body}
        if not self.token:
            marker_path.unlink()
            raise RuntimeError(
                "GITHUB_API token is required for live export (see .env.example)."
            )
        url = f"https://api.github.com/repos/{self.repo}/issues"
        headers = {"Accept": "application/vnd.github+json", "Authorization": f"Bearer {self.token}"}
        try:
            response = self.session.post(url, headers=headers, json={"title": title, "body": body}, timeout=self.timeout)
            response.raise_for_status()
            created = response.json()
        except requests.RequestException as exc:
            marker_path.unlink()
            raise RuntimeError(f"Could not create GitHub issue for export: {exc}") from exc
        marker = {
            "idempotency_key": key,
            "artifact_type": artifact["artifact_type"],
            "source_threat_id": artifact["source_threat_id"],
            "source_card_id": artifact["source_card_id"],
            "github_issue_number": created.get("number"),
            "github_issue_url": created.get("html_url"),
            "model": review_record.get("model"),
            "prompt_template_version": review_record.get("prompt_template_version"),
            "relevance": review_record.get("relevance"),
            "provenance": review_record.get("provenance"),
        }
        marker_path.write_text(json.dumps(marker, indent=2))
        return {"status": "created", "marker": marker}